version: '3.8'
services:
  ubuntu:
    image: ubuntu_hw
    build:
      context: docker-build/
      dockerfile: Dockerfile
    volumes:
      - ./src:/hw_code/

#  docker-compose build
#  docker-compose run ubuntu /bin/bash
#  arm-linux-gnueabi-gcc -marm main.c main.s -o app
#  qemu-arm -L $LINARO_SYSROOT ./app